const API_BASE = window.UKA_API_BASE || "http://127.0.0.1:8877";
const $ = (id) => document.getElementById(id);
const state = { health: null, pendingThread: null, events: [], knowledge: [] };

function context() {
  return { tenant_id: $("tenant-id").value.trim() || "demo-ui", security_scope_id: $("security-scope").value.trim() || "private", actor_id: $("actor-id").value.trim() || "control-room" };
}
function setConnection(kind, label) { const pill = $("connection-pill"); pill.className = `connection-pill ${kind}`; $("connection-label").textContent = label; }
function notice(message, kind = "") { const el = $("ingest-notice"); el.textContent = message; el.className = `notice ${kind}`; el.classList.remove("hidden"); }
function clearNotice() { $("ingest-notice").classList.add("hidden"); }
async function api(path, options = {}) {
  const response = await fetch(`${API_BASE}${path}`, { headers: { "Content-Type": "application/json", ...(options.headers || {}) }, ...options });
  const body = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(`${response.status} · ${body?.detail?.error_type || body?.detail || "API request failed"}`);
  return body;
}
function compact(value, limit = 38) { const text = String(value ?? ""); return text.length > limit ? `${text.slice(0, limit)}…` : text; }
function addEvent(title, detail, status = "COMMITTED") { state.events.unshift({ title, detail, status, time: new Date().toLocaleTimeString("zh-CN", { hour12: false }) }); state.events = state.events.slice(0, 7); renderEvents(); }
function renderEvents() { const el = $("event-list"); if (!state.events.length) { el.innerHTML = `<div class="timeline-empty">还没有活动记录<br /><span>完成一次入库或检索后，这里会出现证据链。</span></div>`; return; } el.innerHTML = state.events.map((event) => `<div class="event-item"><div class="event-rail"></div><div class="event-copy"><strong>${escapeHtml(event.title)}</strong><small class="event-state">${escapeHtml(event.status)} · ${escapeHtml(event.time)}</small><small>${escapeHtml(event.detail)}</small></div></div>`).join(""); }
function escapeHtml(value) { return String(value).replace(/[&<>'"]/g, (char) => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", "'":"&#39;", '"':"&quot;" }[char])); }
function showApproval(result) { const thread = result.thread_id || result.values?.thread_id || result.config?.thread_id; if (!thread) return false; state.pendingThread = thread; $("approval-thread").textContent = `thread ${thread}`; $("approval-drawer").classList.remove("hidden"); $("approval-copy").textContent = `线程 ${thread} 已暂停。系统保留了原始证据，确认后才会进入 active knowledge。`; return true; }
function hideApproval() { state.pendingThread = null; $("approval-drawer").classList.add("hidden"); }
async function loadHealth() { setConnection("", "连接检查中"); try { const health = await api("/health?connect=true"); state.health = health; const safe = health.safe_status || health; $("metric-mode").textContent = String(safe.provider_mode || "—").toUpperCase(); $("metric-model").textContent = safe.llm_model || "deterministic provider"; $("metric-version").textContent = safe.graph_version || "0.1.2"; setConnection("ok", "API 已连接"); addEvent("Provider handshake", `${safe.llm_provider || "local"} · ${safe.llm_model || "deterministic"}`, "HEALTHY"); } catch (error) { setConnection("error", "API 未连接"); $("metric-mode").textContent = "OFFLINE"; $("metric-model").textContent = "请启动 8877 端口后刷新"; notice(`无法连接 ${API_BASE}：${error.message}`, "error"); } }
async function ingest() { clearNotice(); const text = $("source-text").value.trim(); if (!text) { notice("请先粘贴一段原始材料。", "warn"); $("source-text").focus(); return; } const button = $("ingest-button"); button.disabled = true; button.querySelector("span").textContent = "路由与沉淀中…"; try { const result = await api("/v1/ingest", { method:"POST", body: JSON.stringify({ ...context(), text, classification: $("classification").value, auto_approve:false }) }); const thread = result.thread_id || result.values?.thread_id; const outcome = result.status || result.values?.status || result.next_action || "review"; addEvent("Knowledge intake", `${outcome} · ${compact(thread || result.operation_id || "evidence staged")}`, outcome === "completed" ? "COMMITTED" : "REVIEW_REQUIRED"); if (showApproval(result)) notice(`已生成审批线程 ${thread}，请在下方确认。`, "warn"); else notice(`入库完成：${compact(JSON.stringify(result), 150)}`); } catch (error) { notice(`入库失败：${error.message}`, "error"); addEvent("Knowledge intake", error.message, "FAILED"); } finally { button.disabled = false; button.querySelector("span").textContent = "送入知识图谱"; } }
function renderRetrieval(result) { const payload = result.response || result; const pack = payload.evidence_pack || {}; const items = pack.items || []; const unknowns = pack.unknowns || []; const answer = payload.answer || pack.answer || "unknown"; const status = payload.status || result.status || pack.status || "unknown"; $("retrieval-result").innerHTML = `<div class="answer-card"><div class="answer-status"><span>${escapeHtml(String(status).toUpperCase())}</span><span>${items.length} EVIDENCE ITEM${items.length === 1 ? "" : "S"}</span></div><div class="answer-text">${escapeHtml(answer)}</div>${unknowns.length ? `<div class="unknown-line">未知项：${escapeHtml(unknowns.join(" · "))}</div>` : ""}<div class="evidence-list">${items.length ? items.map((item) => `<div class="evidence-item"><span>${escapeHtml(item.evidence_id || item.knowledge_id || item.revision_id || "evidence")}</span><b>${escapeHtml(item.content_hash ? item.content_hash.slice(0, 12) : "TRACEABLE")}</b></div>`).join("") : `<div class="evidence-item"><span>evidence pack empty</span><b>UNKNOWN</b></div>`}</div></div>`; }
async function retrieve() { const query = $("query-text").value.trim(); if (!query) return; const button = $("retrieve-button"); button.disabled = true; button.textContent = "检索中…"; try { const scope = $("domain-scope").value.trim(); const result = await api("/v1/retrieve", { method:"POST", body: JSON.stringify({ ...context(), query, query_scope: scope ? { domain: scope } : {}, limit:5 }) }); renderRetrieval(result); const payload = result.response || result; addEvent("Scoped retrieval", `${String(payload.status || result.status || payload.evidence_pack?.status || "unknown").toUpperCase()} · ${compact(query, 30)}`, "ANSWERED"); } catch (error) { $("retrieval-result").innerHTML = `<div class="notice error">检索失败：${escapeHtml(error.message)}</div>`; addEvent("Scoped retrieval", error.message, "FAILED"); } finally { button.disabled = false; button.innerHTML = `运行检索 <span>⌘ ↵</span>`; } }
async function resume(decision) { const thread = state.pendingThread; if (!thread) return; try { const result = await api(`/v1/threads/${encodeURIComponent(thread)}/resume?tenant_id=${encodeURIComponent(context().tenant_id)}&security_scope_id=${encodeURIComponent(context().security_scope_id)}`, { method:"POST", body:JSON.stringify({ value:{ decision } }) }); addEvent("Human gate", `${decision.toUpperCase()} · ${compact(thread)}`, decision === "approve" ? "APPROVED" : "REJECTED"); hideApproval(); notice(decision === "approve" ? "已批准，知识进入沉淀流程。" : "已拒绝，线程保持可追溯状态。", decision === "approve" ? "" : "warn"); if (result) await refreshThreadEvents(thread); } catch (error) { notice(`审批失败：${error.message}`, "error"); } }
async function refreshThreadEvents(thread) { try { const events = await api(`/v1/threads/${encodeURIComponent(thread)}/events?tenant_id=${encodeURIComponent(context().tenant_id)}&security_scope_id=${encodeURIComponent(context().security_scope_id)}&limit=10`); (Array.isArray(events) ? events : []).slice(0, 3).forEach((event) => addEvent(event.event_type || "thread event", `${event.status || "recorded"} · ${compact(event.event_id || "")}`, String(event.status || "RECORDED").toUpperCase())); } catch (_) {} }
$("refresh-button").addEventListener("click", loadHealth); $("ingest-button").addEventListener("click", ingest); $("retrieve-button").addEventListener("click", retrieve); $("approve-button").addEventListener("click", () => resume("approve")); $("reject-button").addEventListener("click", () => resume("reject")); $("clear-events").addEventListener("click", () => { state.events = []; renderEvents(); }); $("tenant-id").addEventListener("input", () => { $("metric-tenant").textContent = `tenant / ${$("tenant-id").value || "—"}`; }); $("security-scope").addEventListener("input", () => { $("metric-scope").textContent = $("security-scope").value || "—"; $("scope-chip").textContent = $("security-scope").value || "—"; }); document.addEventListener("keydown", (event) => { if (event.key.toLowerCase() === "r" && !["INPUT", "TEXTAREA", "SELECT"].includes(document.activeElement.tagName)) loadHealth(); if ((event.metaKey || event.ctrlKey) && event.key === "Enter") retrieve(); }); loadHealth();
function libraryScope(entry) { return entry.domain_labels?.[0] || entry.domain_ids?.[0] || "unclassified"; }
function libraryTags(entry) { return [...(entry.subjects || []), ...(entry.tasks || [])].filter(Boolean).slice(0, 4); }
function libraryQuery(entry) { const anchor = entry.source_identifiers?.[0] || entry.subjects?.[0] || libraryScope(entry); const task = entry.tasks?.[0] || "关键注意事项"; return `${anchor} ${task}`; }
function renderKnowledge(entries) {
  const grid = $("knowledge-grid");
  const filter = $("library-filter").value.trim().toLowerCase();
  const visible = (entries || []).filter((entry) => !filter || JSON.stringify(entry).toLowerCase().includes(filter));
  $("library-summary").textContent = `${visible.length} 条 active knowledge · ${context().tenant_id} / ${context().security_scope_id}`;
  if (!visible.length) { grid.innerHTML = `<div class="library-empty"><span class="empty-glyph">⌁</span><div><strong>${filter ? "没有匹配的知识词条" : "当前作用域还没有 active knowledge"}</strong><p>${filter ? "换一个领域、主题或关键词试试。" : "完成一次入库并批准后，词条会出现在这里。"}</p></div></div>`; return; }
  grid.innerHTML = visible.map((entry) => {
    const tags = libraryTags(entry);
    const query = libraryQuery(entry);
    return `<article class="knowledge-card"><div class="knowledge-card-top"><span class="domain-badge">${escapeHtml(libraryScope(entry))}</span><span class="knowledge-state">${escapeHtml(String(entry.status || "active").toUpperCase())}</span></div><h3>${escapeHtml(entry.subjects?.[0] || entry.source_identifiers?.[0] || "Knowledge entry")}</h3><p class="knowledge-content">${escapeHtml(entry.content || "")}</p><div class="knowledge-tags">${tags.map((tag) => `<span>${escapeHtml(tag)}</span>`).join("") || `<span>general</span>`}</div><div class="knowledge-meta"><span>confidence <b>${Math.round(Number(entry.confidence || 0) * 100)}%</b></span><span>rev ${escapeHtml(entry.revision || 1)}</span><span>${escapeHtml((entry.evidence_ids || []).length)} evidence</span></div><div class="knowledge-footer"><code>${escapeHtml(entry.knowledge_id || "knowledge")}</code><button class="knowledge-query-button" type="button" data-query="${escapeHtml(query)}" data-domain="${escapeHtml(entry.domain_ids?.[0] || "")}">用于检索 ↗</button></div></article>`;
  }).join("");
  grid.querySelectorAll(".knowledge-query-button").forEach((button) => button.addEventListener("click", () => { $("query-text").value = button.dataset.query || ""; $("domain-scope").value = button.dataset.domain || ""; $("scope-chip").textContent = button.dataset.domain || context().security_scope_id; $("retrieval-result").scrollIntoView({ behavior: "smooth", block: "center" }); $("query-text").focus(); }));
}
async function loadKnowledge() {
  try { const params = new URLSearchParams({ tenant_id: context().tenant_id, security_scope_id: context().security_scope_id, limit: "100" }); const entries = await api(`/v1/knowledge?${params.toString()}`); state.knowledge = Array.isArray(entries) ? entries : []; renderKnowledge(state.knowledge); } catch (error) { $("knowledge-grid").innerHTML = `<div class="library-empty"><span class="empty-glyph">!</span><div><strong>知识库暂时不可用</strong><p>${escapeHtml(error.message)}</p></div></div>`; }
}
$("refresh-library").addEventListener("click", loadKnowledge);
$("library-filter").addEventListener("input", () => renderKnowledge(state.knowledge));
$("tenant-id").addEventListener("change", loadKnowledge);
$("security-scope").addEventListener("change", loadKnowledge);
$("approve-button").addEventListener("click", () => setTimeout(loadKnowledge, 1600));
loadKnowledge();
